//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetImmoBilly
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACHETEURS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACHETEURS()
        {
            this.SOUHAITS = new HashSet<SOUHAITS>();
        }
    
        public int NUMERO_ACHETEUR { get; set; }
        public int NUMERO_VILLE { get; set; }
        public int NUMERO_COMMERCIAL { get; set; }
        public string NOM_ACHETEUR { get; set; }
        public string PRENOM_ACHETEUR { get; set; }
        public string ADRESSE_ACHETEUR { get; set; }
        public string TELEPHONE_PRINCIPAL_ACHETEUR { get; set; }
        public string TELEPHONE_SECONDAIRE_ACHETEUR { get; set; }
        public string EMAIL_ACHETEUR { get; set; }
    
        public virtual COMMERCIAUX COMMERCIAUX { get; set; }
        public virtual VILLES VILLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOUHAITS> SOUHAITS { get; set; }
    }
}
