//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetImmoBilly
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Immobilly_Groupe_SolveigEntities : DbContext
    {
        public Immobilly_Groupe_SolveigEntities()
            : base("name=Immobilly_Groupe_SolveigEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACHETEURS> ACHETEURS { get; set; }
        public virtual DbSet<BIENS> BIENS { get; set; }
        public virtual DbSet<COMMERCIAUX> COMMERCIAUX { get; set; }
        public virtual DbSet<PROPOSITIONS> PROPOSITIONS { get; set; }
        public virtual DbSet<SOUHAITS> SOUHAITS { get; set; }
        public virtual DbSet<STATUT_BIEN> STATUT_BIEN { get; set; }
        public virtual DbSet<STATUT_COMMERCIAUX> STATUT_COMMERCIAUX { get; set; }
        public virtual DbSet<STATUT_SOUHAIT> STATUT_SOUHAIT { get; set; }
        public virtual DbSet<VENDEURS> VENDEURS { get; set; }
        public virtual DbSet<VILLES> VILLES { get; set; }
        public virtual DbSet<VISITES> VISITES { get; set; }
        public virtual DbSet<vueVisite> vueVisite { get; set; }
    }
}
