//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetImmoBilly
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMERCIAUX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMERCIAUX()
        {
            this.ACHETEURS = new HashSet<ACHETEURS>();
        }
    
        public int NUMERO_COMMERCIAL { get; set; }
        public short NUMERO_STATUT_COMMERCIAL { get; set; }
        public string NOM_COMMERCIAL { get; set; }
        public string PRENOM_COMMERCIAL { get; set; }
        public string TELEPHONE_MOBILE_PRO { get; set; }
        public string TELEPHONE_PRIVE { get; set; }
        public string EMAIL_COMMERCIAL { get; set; }
        public string LOGIN { get; set; }
        public string PASS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACHETEURS> ACHETEURS { get; set; }
        public virtual STATUT_COMMERCIAUX STATUT_COMMERCIAUX { get; set; }

        // Redéfinition de la méthode "toString()" afin d'afficher le nom et le prénom d'un commercial dans la grille des acheteurs
        public override string ToString()
        {
            return this.NOM_COMMERCIAL + " " + this.PRENOM_COMMERCIAL;
        }
    }
}
