//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetImmoBilly
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPOSITIONS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROPOSITIONS()
        {
            this.VISITES = new HashSet<VISITES>();
        }
    
        public int NUMERO_PROPOSITION { get; set; }
        public int NUMERO_SOUHAIT { get; set; }
        public int NUMERO_BIEN { get; set; }
        public System.DateTime DATE_PROPOSITION_VISITE { get; set; }
    
        public virtual BIENS BIENS { get; set; }
        public virtual SOUHAITS SOUHAITS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISITES> VISITES { get; set; }
    }
}
