//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetImmoBilly
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOUHAITS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOUHAITS()
        {
            this.PROPOSITIONS = new HashSet<PROPOSITIONS>();
        }
    
        public int NUMERO_SOUHAIT { get; set; }
        public int NUMERO_ACHETEUR { get; set; }
        public int NUMERO_VILLE { get; set; }
        public short NUMERO_STATUT_SOUHAIT { get; set; }
        public Nullable<int> SURFACE_HABITABLE_MINIMALE { get; set; }
        public Nullable<int> SURFACE_PARCELLE_MINIMALE { get; set; }
        public int NOMBRE_PIECE_MINIMALE { get; set; }
        public int PRIX_MAXIMAL { get; set; }
        public Nullable<short> NBCHAMBREMINI { get; set; }
        public Nullable<short> NBSDBMINI { get; set; }
    
        public virtual ACHETEURS ACHETEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROPOSITIONS> PROPOSITIONS { get; set; }
        public virtual STATUT_SOUHAIT STATUT_SOUHAIT { get; set; }
        public virtual VILLES VILLES { get; set; }
    }
}
