//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetImmoBilly
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUT_SOUHAIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public STATUT_SOUHAIT()
        {
            this.SOUHAITS = new HashSet<SOUHAITS>();
        }
    
        public short NUMERO_STATUT_SOUHAIT { get; set; }
        public string LIBELLE_STATUT_SOUHAIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOUHAITS> SOUHAITS { get; set; }

        // Redéfinition de la méthode "toString()" afin d'afficher le statut d'un souhait dans la grille des souhaits d'un acheteur
        public override string ToString()
        {
            return this.LIBELLE_STATUT_SOUHAIT;
        }
    }
}
