//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetImmoBilly
{
    using System;
    using System.Collections.Generic;
    
    public partial class VILLES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VILLES()
        {
            this.ACHETEURS = new HashSet<ACHETEURS>();
            this.BIENS = new HashSet<BIENS>();
            this.SOUHAITS = new HashSet<SOUHAITS>();
            this.VENDEURS = new HashSet<VENDEURS>();
        }
    
        public int NUMERO_VILLE { get; set; }
        public string NOM_VILLE { get; set; }
        public string CODE_POSTAL_VILLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACHETEURS> ACHETEURS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIENS> BIENS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOUHAITS> SOUHAITS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENDEURS> VENDEURS { get; set; }

        // Redéfinition de la méthode "toString()" afin d'afficher le nom et le code postal d'une ville dans la grille des acheteurs et des souhaits
        public override string ToString()
        {
            return this.NOM_VILLE + " - " + this.CODE_POSTAL_VILLE;
        }

    }
}
