//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetImmoBilly
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITES
    {
        public int NUMERO_VISITE { get; set; }
        public int NUMERO_PROPOSITION { get; set; }
        public System.DateTime DATE_VISITE { get; set; }
    
        public virtual PROPOSITIONS PROPOSITIONS { get; set; }

        public override string ToString()
        {
            if(String.IsNullOrEmpty(this.DATE_VISITE.ToString()))
                return "Non Visité";

            return this.DATE_VISITE.ToString();
        }
    }
}
