//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetImmoBilly
{
    using System;
    using System.Collections.Generic;
    
    public partial class vueVisite
    {
        public string acheteur { get; set; }
        public string commercial { get; set; }
        public int NUMERO_BIEN { get; set; }
        public string villeBien { get; set; }
        public System.DateTime DATE_PROPOSITION_VISITE { get; set; }
        public string bienVisite { get; set; }
        public Nullable<System.DateTime> DATE_VISITE { get; set; }
    }
}
